name: my_comics
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_modular: ^4.5.0
  mobx: ^2.0.6+1
  flutter_mobx: ^2.0.4
  flutter_launcher_icons: ^0.9.2
  lottie: ^1.2.2
  shared_preferences: ^2.0.13
  dio: ^4.0.4
  google_fonts: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  mobx_codegen: ^2.0.5+2
  modular_test: ^1.0.1+1
  build_runner: ^2.1.7

flutter:

  uses-material-design: true


  assets:
    - assets/
    
#App launcher Icon
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon_logo.png"
  